version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongo_db

  express-app:
    build:
      context: ../
      dockerfile: ./docker/express/Dockerfile
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://user:password@mongo:27017/mongo_db,
      JWT_SECRET: VGhpcyBpcyBhIHNlY3JldCBleGFtcGxlIHZhbHVlIQ==
    volumes:
      - ../:/usr/src/app
    command: npm start

volumes:
  mongo:
